In [4]:
import numpy as np
data = np.random.random((6, 5))
print(data)
labels = np.random.randint(10, size=(6, 1))
print(labels)

[[0.27215301 0.01048014 0.52044334 0.06389628 0.59950931]
 [0.33627256 0.73162297 0.83541017 0.25462713 0.66192773]
 [0.14247738 0.8289203  0.72738107 0.16414783 0.21911717]
 [0.97890922 0.67795284 0.3307026  0.18431222 0.96993157]
 [0.5073107  0.07352013 0.31895193 0.59688031 0.65695777]
 [0.01845964 0.6771923  0.562302   0.4123248  0.18966236]]
[[3]
 [8]
 [1]
 [2]
 [6]
 [7]]


In [71]:
import csv
all_train_data = []
trainX = []
trainY = []
with open('NSL-KDD/KDDTrain+.txt', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',')
    for row in spamreader:
        all_train_data.append(row)
for i in all_train_data:
    i[1] = protocol_dict[i[1]]
    i[2] = service_dict[i[2]]
    i[3] = flag_dict[i[3]]
    i[-2] = type2id[i[-2]]
    trainX.append(i[:41])
    trainY.append(i[-2])
    
print(trainX[0])
print(trainY[0])

['0', 0, 17, 9, '491', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2', '2', '0.00', '0.00', '0.00', '0.00', '1.00', '0.00', '0.00', '150', '25', '0.17', '0.03', '0.17', '0.00', '0.00', '0.00', '0.05', '0.00']
0


In [15]:
#all_train_data[0][1] = 'tcp'
print(all_train_data[0])
all_label = []
for i in all_train_data:
    all_label.append(i[41])
print(set(all_label))

['0', 'tcp', 'ftp_data', 'SF', '491', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2', '2', '0.00', '0.00', '0.00', '0.00', '1.00', '0.00', '0.00', '150', '25', '0.17', '0.03', '0.17', '0.00', '0.00', '0.00', '0.05', '0.00', 'normal', '20']
{'buffer_overflow', 'portsweep', 'warezclient', 'satan', 'nmap', 'neptune', 'guess_passwd', 'ftp_write', 'smurf', 'perl', 'imap', 'phf', 'rootkit', 'teardrop', 'warezmaster', 'multihop', 'pod', 'loadmodule', 'back', 'normal', 'spy', 'ipsweep', 'land'}


In [33]:
import pandas as pd
all_test_data = pd.read_csv('NSL-KDD/KDDTest+.txt', header=None)

In [17]:
print(all_test_data[0])
all_label_tesr = []
for i in all_test_data:
    all_label_tesr.append(i[41])
print(set(all_label_tesr))

['0', 'tcp', 'private', 'REJ', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '229', '10', '0.00', '0.00', '1.00', '1.00', '0.04', '0.06', '0.00', '255', '10', '0.04', '0.06', '0.00', '0.00', '0.00', '0.00', '1.00', '1.00', 'neptune', '21']
{'buffer_overflow', 'mscan', 'portsweep', 'land', 'sqlattack', 'satan', 'udpstorm', 'nmap', 'neptune', 'guess_passwd', 'worm', 'ftp_write', 'smurf', 'xterm', 'snmpgetattack', 'perl', 'processtable', 'imap', 'phf', 'rootkit', 'snmpguess', 'teardrop', 'sendmail', 'warezmaster', 'ps', 'httptunnel', 'multihop', 'pod', 'loadmodule', 'saint', 'mailbomb', 'back', 'xsnoop', 'normal', 'named', 'xlock', 'ipsweep', 'apache2'}


In [29]:
all_protocol = ['tcp', 'udp', 'icmp']
protocol_dict = {}
for id,name in enumerate(all_protocol):
    protocol_dict[name] = id

all_service = ['aol', 'auth', 'bgp', 'courier', 'csnet_ns', 'ctf', 'daytime', 'discard', 'domain', 'domain_u', 'echo', 'eco_i', 'ecr_i', 'efs', 'exec', 'finger', 'ftp', 'ftp_data', 'gopher', 'harvest', 'hostnames', 'http', 'http_2784', 'http_443', 'http_8001', 'imap4', 'IRC', 'iso_tsap', 'klogin', 'kshell', 'ldap', 'link', 'login', 'mtp', 'name', 'netbios_dgm', 'netbios_ns', 'netbios_ssn', 'netstat', 'nnsp', 'nntp', 'ntp_u', 'other', 'pm_dump', 'pop_2', 'pop_3', 'printer', 'private', 'red_i', 'remote_job', 'rje', 'shell', 'smtp', 'sql_net', 'ssh', 'sunrpc', 'supdup', 'systat', 'telnet', 'tftp_u', 'tim_i', 'time', 'urh_i', 'urp_i', 'uucp', 'uucp_path', 'vmnet', 'whois', 'X11', 'Z39_50']
print(len(all_service))
service_dict = {}
for id,name in enumerate(all_service):
    service_dict[name] = id
    
all_flag = ['OTH', 'REJ', 'RSTO', 'RSTOS0', 'RSTR', 'S0', 'S1', 'S2', 'S3', 'SF', 'SH']
print(len(all_flag))
flag_dict = {}
for id,name in enumerate(all_flag):
    flag_dict[name] = id

70
11


In [62]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(trainX)
trainX = scaler.transform(trainX)

/home/2018110176/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:532: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  FutureWarning)
/home/2018110176/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:532: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  FutureWarning)


In [66]:

print(scaler.transform([trainX[0]]))
print(trainX[0])

[[0.00000000e+00 0.00000000e+00 3.30496041e-02 1.74968492e-02
  9.54550330e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.88818872e-03 3.88818872e-03
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.94409436e-03 0.00000000e+00 0.00000000e+00 2.91614154e-01
  4.86023590e-02 3.30496041e-04 5.83228308e-05 3.30496041e-04
  0.00000000e+00 0.00000000e+00 0.00000000e+00 9.72047180e-05
  0.00000000e+00]]
['0', 0, 17, 9, '491', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2', '2', '0.00', '0.00', '0.00', '0.00', '1.00', '0.00', '0.00', '150', '25', '0.17', '0.03', '0.17', '0.00', '0.00', '0.00', '0.05', '0.00']


/home/2018110176/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:532: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  FutureWarning)


In [70]:
dos_type = ['back','land','neptune','pod','smurf','teardrop']
probing_type = ['ipsweep','nmap','portsweep','satan']
r2l_type = ['ftp_write','guess_passwd','imap','multihop','phf','spy','warezclient','warezmaster']
u2r_type = ['buffer_overflow','loadmodule','perl','rootkit']
type2id = {'normal':0}
for i in dos_type:
    type2id[i] = 1
for i in r2l_type:
    type2id[i] = 2
for i in u2r_type:
    type2id[i] = 3
for i in probing_type:
    type2id[i] = 4